# Generated by Django 4.0.3 on 2022-04-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_user_pub_date_remove_user_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_connect',
            new_name='connect',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_question',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
