# Generated by Django 4.0.3 on 2022-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_rename_user_connect_user_connect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iid',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
