# Generated by Django 4.0.3 on 2022-04-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_user_iid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='iid',
            new_name='idd',
        ),
    ]
